Ft desktop
kemigabocatherine/Personal---Portfolio pull request #2
Opened 2021-12-10 14:20 UTC by kemigabocatherine

2021-12-10 21:28 UTC, Gambit142 requested changes
Hi @kemigabocatherine 👋, 

Good job so far!

## To Highlight
- Good Design 💯 
- Good Pull request Title 💯 
- Good Pull request summary 💯 
- All linters checks 💯 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] Making your `README.md` file more professional by including a _**live demo link**_ and a _**screenshot**_ 🙏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-10 21:28 UTC, Gambit142 commented on top.html
> +                </div>
- [ ] I think the changes you made to the buttons when designing the desktop version affected the outlook of the _**Get my Resume**_ button for the mobile section. It would be nice to fix it so that users who visit your website with their mobile will see a good _**User Interface**_ design.

### The mobile view for the _**Get my Resume**_ button on your design

![image](https://user-images.githubusercontent.com/77106962/145641012-33db9ab0-bc58-4d3a-9c8a-a5301703b446.png)

### The mobile view for the _**Get my Resume**_ button on Figma

![image](https://user-images.githubusercontent.com/77106962/145641158-21168e60-0e97-43b2-ad5d-7b932055f4be.png)

2021-12-10 21:28 UTC, Gambit142 commented on top.html
>              </form>
- [ ] I think the changes you made to the buttons when designing the desktop version affected the outlook of the _**Get in Touch**_ button for the mobile section. It would be nice to fix it so that users who visit your website with their mobile will see a good _**User Interface**_ design.

### The mobile view for the _**Get my Resume**_ button on your design

![image](https://user-images.githubusercontent.com/77106962/145641693-58732a83-36df-41e5-b5ed-7381f2020531.png)

### The mobile view for the _**Get my Resume**_ button on Figma design
![image](https://user-images.githubusercontent.com/77106962/145641858-3f0d63ef-091c-4e55-a5b7-966ed79f55f8.png)

2021-12-10 21:28 UTC, Gambit142 commented on top.html
> +                <a><img class="logo" src="images/LogoPlaceholder.png" alt="My Logo"/></a>
- [ ] (Optional) It would be nice to make the `hamburger` menu for the mobile section visible. That way, the `hamburger` can bring a mobile menu popup when clicked 👍 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/145642260-6ab3f6d5-5398-4cdb-b1bc-642290fe2937.png)

2021-12-10 21:28 UTC, Gambit142 commented on top.html
> +                        <li class="cont">Contact</li>
- [ ] (Optional) It would be nice to wrap the `innerHTML` of the `li` tags in an `<a>` tag. That way, the `li` becomes clickable and reroutes the user to that particular section of your website. 👍

2021-12-11 01:16 UTC, gabrielyea requested changes
Hi @kemigabocatherine , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Suggested changes
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-12-11 01:16 UTC, gabrielyea commented on top.css
> +  }
[OPTIONAL]

- [ ] Please fix the left padding in the input fields, as you can see in the original design is 16px:
```suggestion
  input[type=text],
  input[type=email],
  textarea {
    width: 50%;
    height: 48px;
    border-radius: 2px;
    border: 1px solid #cfd8dc;
    background-color: #fff;
    padding-left: 16px;
    margin-top: 15%;
    margin-left: 25%;
    font-family: Poppins, sans-serif;
    font-weight: 400;
    font-size: 130%;
    color: #172b4d;
  }
```

## Original
![image](https://user-images.githubusercontent.com/28903404/145657984-0b9e36e1-8d54-4cc8-85f9-d41a85a74fe5.png)

## Your design
![image](https://user-images.githubusercontent.com/28903404/145657950-3b7f035e-5bb2-4bbe-a4f1-c4283a84151e.png)

2021-12-11 01:16 UTC, gabrielyea commented on top.css
> +  }
[OPTIONAL]
- [ ] The submit button has a 27 px top margin as shown in the figma template. Please fix it so it looks like the original.

## Original
![image](https://user-images.githubusercontent.com/28903404/145658454-4d1c5c25-5c8e-4c2a-8e67-6f4617c7cefc.png)

## Your design
![image](https://user-images.githubusercontent.com/28903404/145657950-3b7f035e-5bb2-4bbe-a4f1-c4283a84151e.png)

2021-12-11 03:51 UTC, carlos-ssh approved these changes
# 🍾🍾 **STATUS APPROVED** 👏🏽👏🏽

Hi @kemigabocatherine , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



![Approved](https://user-images.githubusercontent.com/22258274/138466108-6b14c541-6a88-44c5-ba76-c64992ac1835.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-11 03:52 UTC, merged