Responsive: Make my personal portfolio a responsive website
kemigabocatherine/Personal---Portfolio pull request #4
Opened 2022-02-16 16:07 UTC by kemigabocatherine

**In this PR;**

- There is the use of media queries to;
- design a responsive website for mobile and desktop devices

2022-02-16 19:32 UTC, mahbubul14 requested changes
# Required Changes ♻️

Hi @kemigabocatherine , 

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

### Mandatory Changes

- [ ] Kindly add a live demo link of the project in your `readme` file.

- [ ] As per your project requirements, you should use at least one Grid for the layout of the elements.

- [ ] Kindly check the comments under the review to see more suggestions. :arrow_down: 

###  To Highlights
:heavy_check_mark: Correct Github flow.
:heavy_check_mark: Descriptive title and summary for the PR.

### Optional Suggestions

- [ ] In the contact section of your readme file, It would be better if you use Author instead of Contact.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-02-16 19:32 UTC, mahbubul14 commented on index.html
> +          </header>
- [ ] For readability, please add two spaces of indentation. Do not use the tab key. You did it throughout your code in the `HTML` file. Please fix others also. For the HTML & CSS best practices we should follow the rules. :writing_hand:

2022-02-16 19:32 UTC, mahbubul14 commented on index.html
> +                  </ul>
- [ ] Kindly fix your navigation item for desktop view :desktop_computer: . It doesn't match the Figma design. Your page looks like now:
![n1](https://user-images.githubusercontent.com/70483835/154341034-1dfaf141-5d5b-4aae-bd2f-6ff7c20cf3a5.png)

2022-02-16 21:46 UTC, mke2111 commented
Project Under Second Opinion Review.
Kindly wait for a response. 😄

2022-02-16 22:10 UTC, mke2111 reviewed
Hello @kemigabocatherine  👋,

_This is an additional review as a result of the second opinion request._

> I will try to make this clarification and I hope by the end we shall all have the same understanding of the request.

It is a best practice to have an indentation of 2 spaces for HTML as well. This does not only apply to CSS. As mentioned in the [HTML & CSS best practices article](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md), specifically, option 3. You can set up your favorite code editor to have a default spacing of 2 even when you use the `tab` key.

Make these requested changes and submit another CRR whenever you are ready.

Keep rocking 🚀!

2022-02-17 20:20 UTC, BenMukebo approved these changes
Hi @kemigabocatherine , 👋 

# STATUS: Approved  🎉 
Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

<img src="https://media3.giphy.com/media/29rsFlMw8wLlxOCPH1/giphy.gif"/>
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 20:39 UTC, merged