Feature middle
kemigabocatherine/Personal---Portfolio pull request #4
Opened 2021-11-24 12:58 UTC by kemigabocatherine

2021-11-24 20:02 UTC, andersonlebon requested changes
Hi @kemigabocatherine 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] In the README your section `Getting started` should not explain the steps you used while building this project rather it should explain how someone else can run or get the project in his/her local environment. you can include something like:
```
To get the content of this project locally you need to run this command in your terminal:
- `git clone yourlink`
- `cd project name
```
- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-24 21:31 UTC, andersonlebon commented on top.html
> +        <div class="project2">
- [ ] The work projects section should be a `<section>` tag. Kindly let's put all projects in one  `<section>` tag, I know you can do it :clap: :clap: 
- [ ] The  work projects section should use` display:grid`

2021-11-24 21:31 UTC, andersonlebon commented on top.html
> +            <button class="resume" type="button">Get my resume</button>
- [ ] The button ( "Get my resume") is a link `a` or `button` tag, and follow the button styling: Active, Hover, and Pressed (see design)
![Screenshot from 2021-11-24 23-19-42](https://user-images.githubusercontent.com/65068771/143314708-06c1b289-7430-402c-b4c2-0f5f287815b6.png)

2021-11-24 21:31 UTC, andersonlebon commented on top.html
> +                </div>
- [ ] The technology categories ("Languages", "Frameworks" and "Skills") are in a `<ul>`, each of them in a `<li>`

2021-11-24 21:31 UTC, andersonlebon commented on top.html
> +            </div>
The technology in each category( "JavasScript", "HTML" and "CSS") are also a list `ul` and each of them a `li`

2021-11-24 21:31 UTC, andersonlebon commented on top.html
> +            <button type="button" class="pro1">See Project</button>
- [ ] The button (e.g., "See project") is a link `a` or `button` tag, and follow the button styling: Active, Hover and Pressed (see design)
![Screenshot from 2021-11-24 23-19-42](https://user-images.githubusercontent.com/65068771/143315229-4abf1c8a-d3f3-44f2-b562-d02fac096c1c.png)

2021-11-25 20:42 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED ✔🎉**
Hello @kemigabocatherine 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 21:03 UTC, merged